variables:
  - &jdk "chainguard/jdk"

steps:
  prettier_markdown_check:
    image: tmknom/prettier
    commands:
      - prettier -c "*.md" "*.yml"
    when:
      - event: pull_request

  check_formatting:
    image: *jdk
    commands:
      - ./gradlew lintKotlin
    environment:
      GRADLE_USER_HOME: ".gradle"
    when:
      - event: pull_request

  build_project:
    image: *jdk
    commands:
      - ./gradlew build
    environment:
      GRADLE_USER_HOME: ".gradle"
    when:
      - event: pull_request

  run_tests:
    image: *jdk
    commands:
      - ./gradlew test
    environment:
      GRADLE_USER_HOME: ".gradle"
    when:
      - event: pull_request

  notify_success:
    image: alpine:3
    commands:
      - apk add curl
      - "curl -H'Title: ✔️ ${CI_REPO_NAME}/${CI_COMMIT_SOURCE_BRANCH}' -d'${CI_PIPELINE_URL}' ntfy.sh/pretty_num_kotlin_ci"
    when:
      - event: pull_request
        status: [success]

  notify_failure:
    image: alpine:3
    commands:
      - apk add curl
      - "curl -H'Title: ❌ ${CI_REPO_NAME}/${CI_COMMIT_SOURCE_BRANCH}' -d'${CI_PIPELINE_URL}' ntfy.sh/pretty_num_kotlin_ci"
    when:
      - event: pull_request
        status: [failure]

  notify_on_tag_deploy:
    image: alpine:3
    commands:
      - apk add curl
      - "curl -H'Title: ${CI_REPO_NAME}:${CI_COMMIT_TAG} deployed' -d'${CI_PIPELINE_URL}' ntfy.sh/pretty_num_kotlin_ci"
    when:
      event: tag
