/*
 * This source file was generated by the Gradle 'init' task
 */
package com.dessalines

import kotlin.test.Test
import kotlin.test.assertTrue

class PrettyNumTest {
    fun test(
        num: Long,
        expected: String,
    ) {
        assertTrue(prettyFormat(num).equals(expected))
    }

    @Test
    fun tests() {
        test(7, "7")
        test(42, "42")
        test(717, "717")
        test(-5, "-5")
        test(-76, "-76")
        test(-224, "-224")
        test(1_001, "1k")
        test(1_624, "1.6k")
        test(-5_020, "-5k")
        test(-9_505, "-9.5k")
        test(19_007, "19k")
        test(73_444, "73.4k")
        test(-55_033, "-55k")
        test(-42_780, "-42.8k")
        test(469_070, "469k")
        test(945_661, "946k")
        test(-223_090, "-223k")
        test(-671_522, "-672k")
        test(3_001_500, "3M")
        test(7_926_400, "7.9M")
        test(-4_030_115, "-4M")
        test(-3_333_221, "-3.3M")
        test(75_032_115, "75M")
        test(23_333_452, "23.3M")
        test(-54_012_560, "-54M")
        test(-11_740_662, "-11.7M")
        test(555_067_885, "555M")
        test(352_344_120, "352M")
        test(-222_000_554, "-222M")
        test(-434_875_500, "-435M")
        test(2_004_254_578, "2B")
        test(7_667_973_223, "7.7B")
        test(-4_002_154_900, "-4B")
        test(-6_534_664_725, "-6.5B")
        test(87_050_671_768, "87B")
        test(44_444_333_222, "44.4B")
        test(-32_010_345_093, "-32B")
        test(-65_420_132_543, "-65.4B")
        test(899_055_111_032, "899B")
        test(723_999_324_999, "724B")
        test(-666_000_142_543, "-666B")
        test(-400_601_897_231, "-401B")
        test(5_000_023_667_158, "5T")
        test(1_222_333_444_555, "1.2T")
        test(-4_000_354_984_333, "-4T")
        test(-6_923_000_178_126, "-6.9T")
        test(66_001_789_809_223, "66T")
        test(93_723_000_151_300, "93.7T")
        test(-50_032_745_113_006, "-50T")
        test(-11_444_653_221_094, "-11.4T")
        test(343_003_766_091_322, "343T")
        test(357_455_634_091_722, "357T")
        test(-567_023_400_999_234, "-567T")
        test(-871_567_223_222_546, "-872T")
    }
}
